In [1]:
import pandas as pd
from sqlalchemy import create_engine
from config import password
from datetime import datetime

In [2]:
player_filepath = "Resources/basketball_player_allstar.csv"
player_df = pd.read_csv(player_filepath)
player_df.head()

,player_id,last_name,first_name,season_id,conference,league_id,games_played,minutes,points,o_rebounds,...,steals,blocks,turnovers,personal_fouls,fg_attempted,fg_made,ft_attempted,ft_made,three_attempted,three_made
0,abdulka01,Abdul-Jabbar,Kareem,1978,West,NBA,1,28,11.0,NaN,...,NaN,NaN,NaN,NaN,12.0,5.0,2.0,1.0,NaN,NaN
1,abdulka01,Abdul-Jabbar,Kareem,1969,East,NBA,1,18,10.0,NaN,...,NaN,NaN,NaN,NaN,8.0,4.0,2.0,2.0,NaN,NaN
2,abdulka01,Abdul-Jabbar,Kareem,1988,West,NBA,1,13,4.0,NaN,...,NaN,NaN,NaN,NaN,6.0,1.0,2.0,2.0,NaN,NaN
3,abdulka01,Abdul-Jabbar,Kareem,1987,West,NBA,1,14,10.0,NaN,...,NaN,NaN,NaN,NaN,9.0,4.0,2.0,2.0,NaN,NaN
4,abdulka01,Abdul-Jabbar,Kareem,1986,West,NBA,1,27,10.0,NaN,...,NaN,NaN,NaN,NaN,9.0,4.0,2.0,2.0,NaN,NaN

In [3]:
game_filepath = "Resources/NBA_All_Star_Games.xlsx"
game_df = pd.read_excel(game_filepath)
game_df.head()

,Year,Player,Pos,HT,WT,Team,Selection Type,NBA Draft Status,Nationality
0,2016,Stephen Curry,G,2017-06-03 00:00:00,190,Golden State Warriors,Western All-Star Fan Vote Selection,2009 Rnd 1 Pick 7,United States
1,2016,James Harden,SG,2017-06-05 00:00:00,220,Houston Rockets,Western All-Star Fan Vote Selection,2009 Rnd 1 Pick 3,United States
2,2016,Kevin Durant,SF,2017-06-09 00:00:00,240,Golden State Warriors,Western All-Star Fan Vote Selection,2007 Rnd 1 Pick 2,United States
3,2016,Kawhi Leonard,F,2017-06-07 00:00:00,230,San Antonio Spurs,Western All-Star Fan Vote Selection,2011 Rnd 1 Pick 15,United States
4,2016,Anthony Davis,PF,2017-06-11 00:00:00,253,New Orleans Pelicans,Western All-Star Fan Vote Selection,2012 Rnd 1 Pick 1,United States

In [4]:
player_df = player_df.loc[player_df['season_id'] >= 2000]
player_df['full_name'] = player_df['first_name'] + " " +  player_df['last_name']
player_df['full_name']
player_df.head()

,player_id,last_name,first_name,season_id,conference,league_id,games_played,minutes,points,o_rebounds,...,blocks,turnovers,personal_fouls,fg_attempted,fg_made,ft_attempted,ft_made,three_attempted,three_made,full_name
19,abdursh01,A-Rahim,Shareef,2001,East,NBA,1,21,9.0,1.0,...,0.0,0.0,2.0,4.0,4.0,0.0,0.0,1.0,1.0,Shareef A-Rahim
26,allenra02,Allen,Ray,2001,East,NBA,1,25,15.0,1.0,...,0.0,1.0,3.0,17.0,6.0,0.0,0.0,10.0,3.0,Ray Allen
27,allenra02,Allen,Ray,2000,East,NBA,1,19,15.0,1.0,...,1.0,1.0,0.0,15.0,7.0,0.0,0.0,7.0,1.0,Ray Allen
29,allenra02,Allen,Ray,2003,West,NBA,1,23,16.0,2.0,...,0.0,3.0,2.0,13.0,6.0,4.0,3.0,4.0,1.0,Ray Allen
30,allenra02,Allen,Ray,2008,East,NBA,1,18,8.0,1.0,...,0.0,1.0,0.0,10.0,4.0,0.0,0.0,3.0,0.0,Ray Allen

In [5]:
player_df.dropna()
player_df.head()

,player_id,last_name,first_name,season_id,conference,league_id,games_played,minutes,points,o_rebounds,...,blocks,turnovers,personal_fouls,fg_attempted,fg_made,ft_attempted,ft_made,three_attempted,three_made,full_name
19,abdursh01,A-Rahim,Shareef,2001,East,NBA,1,21,9.0,1.0,...,0.0,0.0,2.0,4.0,4.0,0.0,0.0,1.0,1.0,Shareef A-Rahim
26,allenra02,Allen,Ray,2001,East,NBA,1,25,15.0,1.0,...,0.0,1.0,3.0,17.0,6.0,0.0,0.0,10.0,3.0,Ray Allen
27,allenra02,Allen,Ray,2000,East,NBA,1,19,15.0,1.0,...,1.0,1.0,0.0,15.0,7.0,0.0,0.0,7.0,1.0,Ray Allen
29,allenra02,Allen,Ray,2003,West,NBA,1,23,16.0,2.0,...,0.0,3.0,2.0,13.0,6.0,4.0,3.0,4.0,1.0,Ray Allen
30,allenra02,Allen,Ray,2008,East,NBA,1,18,8.0,1.0,...,0.0,1.0,0.0,10.0,4.0,0.0,0.0,3.0,0.0,Ray Allen

In [6]:
player_df.columns

Index(['player_id', 'last_name', 'first_name', 'season_id', 'conference',
       'league_id', 'games_played', 'minutes', 'points', 'o_rebounds',
       'd_rebounds', 'rebounds', 'assists', 'steals', 'blocks', 'turnovers',
       'personal_fouls', 'fg_attempted', 'fg_made', 'ft_attempted', 'ft_made',
       'three_attempted', 'three_made', 'full_name'],
      dtype='object')

In [7]:
columns_player = ['player_id', 'last_name', 'first_name', 'year', 'conference',
       'league_id', 'games_played', 'minutes', 'points', 'offensive_rebounds',
       'defensive_rebounds', 'total_rebounds', 'assists', 'steals', 'blocks', 'turnovers',
       'personal_fouls', 'field_goals_attempted', 'field_goals_made', 'free_throws_attempted', 'free_throw_made',
       'three_points_attempted', 'three_points_made', 'player']
player_df.columns = columns_player
player_df.head()

,player_id,last_name,first_name,year,conference,league_id,games_played,minutes,points,offensive_rebounds,...,blocks,turnovers,personal_fouls,field_goals_attempted,field_goals_made,free_throws_attempted,free_throw_made,three_points_attempted,three_points_made,player
19,abdursh01,A-Rahim,Shareef,2001,East,NBA,1,21,9.0,1.0,...,0.0,0.0,2.0,4.0,4.0,0.0,0.0,1.0,1.0,Shareef A-Rahim
26,allenra02,Allen,Ray,2001,East,NBA,1,25,15.0,1.0,...,0.0,1.0,3.0,17.0,6.0,0.0,0.0,10.0,3.0,Ray Allen
27,allenra02,Allen,Ray,2000,East,NBA,1,19,15.0,1.0,...,1.0,1.0,0.0,15.0,7.0,0.0,0.0,7.0,1.0,Ray Allen
29,allenra02,Allen,Ray,2003,West,NBA,1,23,16.0,2.0,...,0.0,3.0,2.0,13.0,6.0,4.0,3.0,4.0,1.0,Ray Allen
30,allenra02,Allen,Ray,2008,East,NBA,1,18,8.0,1.0,...,0.0,1.0,0.0,10.0,4.0,0.0,0.0,3.0,0.0,Ray Allen

In [8]:
del player_df['player_id']
del player_df['last_name']
del player_df['first_name']
player_df.head()

,year,conference,league_id,games_played,minutes,points,offensive_rebounds,defensive_rebounds,total_rebounds,assists,...,blocks,turnovers,personal_fouls,field_goals_attempted,field_goals_made,free_throws_attempted,free_throw_made,three_points_attempted,three_points_made,player
19,2001,East,NBA,1,21,9.0,1.0,5.0,6.0,0.0,...,0.0,0.0,2.0,4.0,4.0,0.0,0.0,1.0,1.0,Shareef A-Rahim
26,2001,East,NBA,1,25,15.0,1.0,2.0,3.0,5.0,...,0.0,1.0,3.0,17.0,6.0,0.0,0.0,10.0,3.0,Ray Allen
27,2000,East,NBA,1,19,15.0,1.0,2.0,3.0,2.0,...,1.0,1.0,0.0,15.0,7.0,0.0,0.0,7.0,1.0,Ray Allen
29,2003,West,NBA,1,23,16.0,2.0,1.0,3.0,4.0,...,0.0,3.0,2.0,13.0,6.0,4.0,3.0,4.0,1.0,Ray Allen
30,2008,East,NBA,1,18,8.0,1.0,2.0,3.0,1.0,...,0.0,1.0,0.0,10.0,4.0,0.0,0.0,3.0,0.0,Ray Allen

In [9]:
game_df = game_df.loc[game_df['Year'] <= 2009]

In [10]:
game_df

,Year,Player,Pos,HT,WT,Team,Selection Type,NBA Draft Status,Nationality
178,2009,Deron Williams,PG,2017-06-03 00:00:00,200,Utah Jazz,Western All-Star Coaches Selection,2005 Rnd 1 Pick 3,United States
179,2009,Chris Paul,PG,6-0,175,New Orleans Hornets,Western All-Star Coaches Selection,2005 Rnd 1 Pick 4,United States
180,2009,Pau Gasol,FC,7-0,250,Los Angeles Lakers,Western All-Star Coaches Selection,2001 Rnd 1 Pick 3,Spain
181,2009,Kevin Durant,SF,2017-06-09 00:00:00,240,Oklahoma City Thunder,Western All-Star Coaches Selection,2007 Rnd 1 Pick 2,United States
182,2009,Dirk Nowitzki,PF,7-0,245,Dallas Mavericks,Western All-Star Coaches Selection,1998 Rnd 1 Pick 9,Germany
183,2009,Zach Randolph,PF,2017-06-09 00:00:00,260,Memphis Grizzlies,Western All-Star Coaches Selection,2001 Rnd 1 Pick 19,United States
184,2009,Brandon Roy,G,2017-06-06 00:00:00,211,Portland Trail Blazers,Western All-Star Coaches Selection,2006 Rnd 1 Pick 6,United States
185,2009,Steve Nash,G,2017-06-03 00:00:00,178,Phoenix Suns,Western All-Star Fan Vote Selection,1996 Rnd 1 Pick 15,Canada\nSouth Africa
186,2009,Kobe Bryant,SG,2017-06-06 00:00:00,212,Los Angeles Lakers,Western All-Star Fan Vote Selection,1996 Rnd 1 Pick 13,United States
187,2009,Amar'e Stoudemire,FC,2017-06-10 00:00:00,245,Phoenix Suns,Western All-Star Fan Vote Selection,2002 Rnd 1 Pick 9,United States
188,2009,Tim Duncan,FC,2017-06-11 00:00:00,250,San Antonio Spurs,Western All-Star Fan Vote Selection,1997 Rnd 1 Pick 1,United States
189,2009,Carmelo Anthony,F,2017-06-08 00:00:00,240,Denver Nuggets,Western All-Star Fan Vote Selection,2003 Rnd 1 Pick 3,United States
190,2009,Chauncey Billups,G,2017-06-03 00:00:00,210,Denver Nuggets,Western All-Star Replacement Selection,1997 Rnd 1 Pick 3,United States
191,2009,Chris Kaman,C,7-0,265,Los Angeles Clippers,Western All-Star Replacement Selection,2003 Rnd 1 Pick 6,United States\nGermany
192,2009,Jason Kidd,PG,2017-06-04 00:00:00,210,Dallas Mavericks,Western All-Star Replacement Selection,1994 Rnd 1 Pick 2,United States
193,2009,LeBron James,F,2017-06-08 00:00:00,250,Cleveland Cavaliers,Eastern All-Star Fan Vote Selection,2003 Rnd 1 Pick 1,United States
194,2009,Kevin Garnett,PF,2017-06-11 00:00:00,240,Boston Celtics,Eastern All-Star Fan Vote Selection,1995 Rnd 1 Pick 5,United States
195,2009,Allen Iverson,G,6-0,165,Philadelphia Sixers,Eastern All-Star Fan Vote Selection,1996 Rnd 1 Pick 1,United States
196,2009,Dwyane Wade,SG,2017-06-04 00:00:00,220,Miami Heat,Eastern All-Star Fan Vote Selection,2003 Rnd 1 Pick 5,United States
197,2009,Dwight Howard,C,2017-06-11 00:00:00,265,Orlando Magic,Eastern All-Star Fan Vote Selection,2004 Rnd 1 Pick 1,United States
198,2009,Rajon Rondo,PG,2017-06-01 00:00:00,186,Boston Celtics,Eastern All-Star Coaches Selection,2006 Rnd 1 Pick 21,United States
199,2009,Derrick Rose,PG,2017-06-03 00:00:00,190,Chicago Bulls,Eastern All-Star Coaches Selection,2008 Rnd 1 Pick 1,United States
200,2009,Paul Pierce,SF,2017-06-07 00:00:00,235,Boston Celtics,Eastern All-Star Coaches Selection,1998 Rnd 1 Pick 10,United States
201,2009,Chris Bosh,PF,2017-06-11 00:00:00,235,Toronto Raptors,Eastern All-Star Coaches Selection,2003 Rnd 1 Pick 4,United States
202,2009,Gerald Wallace,F,2017-06-07 00:00:00,220,Charlotte Bobcats,Eastern All-Star Coaches Selection,2001 Rnd 1 Pick 25,United States
203,2009,Joe Johnson,SG,2017-06-07 00:00:00,240,Atlanta Hawks,Eastern All-Star Coaches Selection,2001 Rnd 1 Pick 10,United States
204,2009,Al Horford,FC,2017-06-10 00:00:00,245,Atlanta Hawks,Eastern All-Star Coaches Selection,2007 Rnd 1 Pick 3,Dominican Republic\nUnited States
205,2009,David Lee,FC,2017-06-09 00:00:00,245,New York Knicks,Eastern All-Star Replacement Selection,2005 Rnd 1 Pick 30,United States
206,2008,Chauncey Billups,G,2017-06-03 00:00:00,210,Denver Nuggets,Western All-Star Coaches Selection,1997 Rnd 1 Pick 3,United States
207,2008,Pau Gasol,FC,7-0,250,Los Angeles Lakers,Western All-Star Coaches Selection,2001 Rnd 1 Pick 3,Spain
...,...,...,...,...,...,...,...,...,...
409,2001,Chris Webber,F-C,2017-06-09 00:00:00,245,Sacramento Kings,Western All-Star Coaches Selection,1993 Rnd 1 Pick 1,United States
410,2001,Elton Brand,PF,2017-06-09 00:00:00,254,Los Angeles Clippers,Western All-Star Replacement Selection,1999 Rnd 1 Pick 1,United States
411,2000,Allen Iverson,G,6-0,165,Philadelphia Sixers,Eastern All-Star Fan Vote Selection,1996 Rnd 1 Pick 1,United States
412,2000,Tracy McGrady,GF,2017-06-08 00:00:00,210,Orlando Magic,Eastern All-Star Fan Vote Selection,1997 Rnd 1 Pick 9,United States
413,2000,Vince Carter,SF,2017-06-06 00:00:00,220,Toronto Raptors,Eastern All-Star Fan Vote Selection,1998 Rnd 1 Pick 5,United States
414,2000,Alonzo Mourning,C,2017-06-10 00:00:00,240,Miami Heat,Eastern All-Star Fan Vote Selection,1992 Rnd 1 Pick 2,United States
415,2000,Grant Hill,SF,2017-06-08 00:00:00,225,Orlando Magic,Eastern All-Star Fan Vote Selection,1994 Rnd 1 Pick 3,United States
416,2000,Ray Allen,SG,2017-06-05 00:00:00,205,Milwaukee Bucks,Eastern All-Star Coaches Selection,1996 Rnd 1 Pick 5,United States
417,2000,Antonio Davis,FC,2017-06-09 00:00:00,245,Toronto Raptors,Eastern All-Star Replacement Selection,1990 Rnd 2 Pick 18,United States
418,2000,Theo Ratliff,C,2017-06-10 00:00:00,235,Philadelphia Sixers,Eastern All-Star Coaches Selection,1995 Rnd 1 Pick 18,United States
419,2000,Glenn Robinson,SF,2017-06-07 00:00:00,225,Milwaukee Bucks,Eastern All-Star Coaches Selection,1994 Rnd 1 Pick 1,United States
420,2000,Jerry Stackhouse,SF,2017-06-06 00:00:00,218,Detroit Pistons,Eastern All-Star Coaches Selection,1995 Rnd 1 Pick 3,United States
421,2000,Stephon Marbury,G,2017-06-02 00:00:00,180,New Jersey Nets,Eastern All-Star Coaches Selection,1996 Rnd 1 Pick 4,United States
422,2000,Anthony Mason,PF,2017-06-07 00:00:00,250,Miami Heat,Eastern All-Star Coaches Selection,1988 Rnd 3 Pick 3,United States
423,2000,Dikembe Mutombo,C,2017-07-02 00:00:00,260,Atlanta Hawks,Eastern All-Star Replacement Selection,1991 Rnd 1 Pick 4,Democratic Republic of the Congo
424,2000,Latrell Sprewell,SG,2017-06-05 00:00:00,190,New York Knicks,Eastern All-Star Replacement Selection,1992 Rnd 1 Pick 24,United States
425,2000,Allan Houston,G,2017-06-06 00:00:00,205,New York Knicks,Eastern All-Star Coaches Selection,1993 Rnd 1 Pick 11,United States
426,2000,Jason Kidd,PG,2017-06-04 00:00:00,210,Phoenix Suns,Western All-Star Fan Vote Selection,1994 Rnd 1 Pick 2,United States
427,2000,Kobe Bryant,SG,2017-06-06 00:00:00,212,Los Angeles Lakers,Western All-Star Fan Vote Selection,1996 Rnd 1 Pick 13,United States
428,2000,Tim Duncan,FC,2017-06-11 00:00:00,250,San Antonio Spurs,Western All-Star Fan Vote Selection,1997 Rnd 1 Pick 1,United States
429,2000,Shaquille O'Neal,C,2017-07-01 00:00:00,325,Los Angeles Lakers,Western All-Star Fan Vote Selection,1992 Rnd 1 Pick 1,United States
430,2000,Chris Webber,F-C,2017-06-09 00:00:00,245,Sacramento Kings,Western All-Star Fan Vote Selection,1993 Rnd 1 Pick 1,United States
431,2000,Michael Finley,G-F,2017-06-07 00:00:00,225,Dallas Mavericks,Western All-Star Coaches Selection,1995 Rnd 1 Pick 21,United States
432,2000,Kevin Garnett,PF,2017-06-11 00:00:00,240,Minnesota Timberwolves,Western All-Star Coaches Selection,1995 Rnd 1 Pick 5,United States
433,2000,Karl Malone,PF,2017-06-09 00:00:00,265,Utah Jazz,Western All-Star Coaches Selection,1985 Rnd 1 Pick 13,United States
434,2000,Antonio McDyess,F,2017-06-09 00:00:00,245,Denver Nuggets,Western All-Star Coaches Selection,1995 Rnd 1 Pick 2,United States
435,2000,Gary Payton,G,2017-06-04 00:00:00,180,Seattle SuperSonics,Western All-Star Coaches Selection,1990 Rnd 1 Pick 2,United States
436,2000,Rasheed Wallace,FC,2017-06-11 00:00:00,230,Portland Trail Blazers,Western All-Star Coaches Selection,1995 Rnd 1 Pick 4,United States
437,2000,David Robinson,C,2017-07-01 00:00:00,250,San Antonio Spurs,Western All-Star Coaches Selection,1987 Rnd 1 Pick 1,United States
438,2000,Vlade Divac,C,2017-07-01 00:00:00,260,Sacramento Kings,Western All-Star Replacement Selection,1989 Rnd 1 Pick 26,Serbia

In [11]:
## Height Dateobj to string
height = []

for game in game_df['HT']:
    if not isinstance(game, str):
        height.append(game.strftime("%m-%d").replace("0", ""))
    else:
        height.append(game)

In [12]:
game_df.insert(3, 'height', height)
del game_df['HT']

In [13]:
game_df.columns

Index(['Year', 'Player', 'Pos', 'height', 'WT', 'Team', 'Selection Type',
       'NBA Draft Status', 'Nationality'],
      dtype='object')

In [14]:
columns_game = ['year', 'player', 'position', 'height', 'weight', 'team', 'selection',
       'nba_draft_status', 'home_country']
game_df.columns = columns_game
game_df.head()

,year,player,position,height,weight,team,selection,nba_draft_status,home_country
178,2009,Deron Williams,PG,6-3,200,Utah Jazz,Western All-Star Coaches Selection,2005 Rnd 1 Pick 3,United States
179,2009,Chris Paul,PG,6-0,175,New Orleans Hornets,Western All-Star Coaches Selection,2005 Rnd 1 Pick 4,United States
180,2009,Pau Gasol,FC,7-0,250,Los Angeles Lakers,Western All-Star Coaches Selection,2001 Rnd 1 Pick 3,Spain
181,2009,Kevin Durant,SF,6-9,240,Oklahoma City Thunder,Western All-Star Coaches Selection,2007 Rnd 1 Pick 2,United States
182,2009,Dirk Nowitzki,PF,7-0,245,Dallas Mavericks,Western All-Star Coaches Selection,1998 Rnd 1 Pick 9,Germany

In [15]:
engine = create_engine('postgresql://postgres:'+ password +'@localhost:5432/NbaAllstar')
connection = engine.connect()
# Confirm tables
engine.table_names()

['allstar_players', 'allstar_games']

In [16]:
player_df.to_sql(name='allstar_players', con=engine, if_exists='replace', index=False)

In [17]:
game_df.to_sql(name='allstar_games', con=engine, if_exists='replace', index=False)

In [18]:
player_df.columns

Index(['year', 'conference', 'league_id', 'games_played', 'minutes', 'points',
       'offensive_rebounds', 'defensive_rebounds', 'total_rebounds', 'assists',
       'steals', 'blocks', 'turnovers', 'personal_fouls',
       'field_goals_attempted', 'field_goals_made', 'free_throws_attempted',
       'free_throw_made', 'three_points_attempted', 'three_points_made',
       'player'],
      dtype='object')